language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
install: 
  - npm install
after_success:
  - npm i -g travis-deploy-once
  - npm run travis-deploy-once "npm run build && npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
